### PR TITLE
Adding Inventory Display and Sprite control

### PR DESCRIPTION
**Pull request by kcmcg**
Started digging through the code using bgb in the parts that render the inventory menu and that control inventory drops when killing bosses and rendering those dropped sprites. Discoveries include:

-Added 5 new banks from a disassembly generated by mgbdis along with some comments in each of those banks.
-Added inventory and chest constants to a new constants file
-Found full list of sprite rendering pointers
-Found full list of map chest IDs

### CODE REVIEW

**Comment by kemenaran** [comment]
Wow, this looks great! It definitely seems a nice piece of work. I'll have a look at the code as soon as I can (probably in the next few days).

Just one thing: I usually merge code into the parent repository ([mojobojo/LADX-Disassembly](https://github.com/mojobojo/LADX-Disassembly)), which is more up-to-date (I use my forked repository mostly to push branches, but they are merged upstream).

Would you mind submitting your PR on the latest `master` branch of [mojobojo/LADX-Disassembly](https://github.com/mojobojo/LADX-Disassembly)? (Otherwise if for any reason it's too complicated I probably re-submit the PR myself on the parent repo).

**Comment by kcmcg** [comment]
Yeah, no problem. Wasn't sure which repository to put the pull request on, so I'll try to merge my changes with the latest branch on the mojobojo/LADX-Disassembly repo and move the pull request there.

**Comment by kemenaran** [comment]
Hey @kcmcg! I started looking at this project again (on the main https://github.com/mojobojo/LADX-Disassembly repository), and so I found myself looking at your PR again.

There is definitely a lot of nice work in it. Just to say I didn't forget you: I'll try to rebase this code on the latest master version – and if it diverged too much, I'll port the useful bits, infos and comments manually.

**Comment by kcmcg** [comment]
Yeah @kemenaran, I'm sorry that I kind of let this drop off my radar. I still wanted to reapply my changes to the latest master and never got back to it. Should I recreate my PR on the main repo or should I wait until I can rebase?

**Comment by kemenaran** [comment]
I'm fine with reading this PR on this repo. And if at some point you can rebase it, then I guess it will be a good time to open it on the main repo :)

**Pull request closed without merging**
